# Generated by Django 5.2.6 on 2025-10-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_unique_together_and_more'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'opportunity')},
        ),
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='manual_company_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='manual_job_title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='manual_location',
        ),
    ]
