# Generated by Django 5.2.6 on 2025-10-09 12:32

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing records"""
    Discussion = apps.get_model('forum', 'Discussion')
    ForumCategory = apps.get_model('forum', 'ForumCategory')
    
    # Populate category slugs
    for category in ForumCategory.objects.all():
        if not category.slug:
            category.slug = slugify(category.name)
            category.save()
    
    # Populate discussion slugs
    for discussion in Discussion.objects.all():
        if not discussion.slug:
            base_slug = slugify(discussion.title)
            slug = base_slug
            counter = 1
            while Discussion.objects.filter(slug=slug).exclude(id=discussion.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            discussion.slug = slug
            discussion.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        # First, add the fields without unique constraint
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=False),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=False),
        ),
        # Populate the slugs
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Now make the fields unique
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
