# Generated by Django 5.2.6 on 2025-09-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='mentors.mentorprofile'),
        ),
        migrations.CreateModel(
            name='MentorSpecificAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for unavailability', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_availability', to='mentors.mentorprofile')),
            ],
            options={
                'db_table': 'mentor_specific_availability',
                'ordering': ['date', 'start_time'],
                'unique_together': {('mentor', 'date', 'start_time')},
            },
        ),
    ]
