# Generated by Django 5.2.6 on 2025-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentoravailability_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoravailability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
