# Generated by Django 5.2.6 on 2025-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentorshipsession_mentee_mentorshipsession_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='mentorship_request',
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
