# Generated by Django 5.2.6 on 2025-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_remove_mentorshipsession_mentorship_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
