# Generated by Django 5.2.6 on 2025-09-12 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('goal_type', models.CharField(choices=[('career_change', 'Career Change'), ('skill_development', 'Skill Development'), ('job_search', 'Job Search'), ('education', 'Education'), ('networking', 'Networking'), ('promotion', 'Promotion'), ('salary_increase', 'Salary Increase'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_goals',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_habits',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tracker.goal')),
            ],
            options={
                'db_table': 'tracker_milestones',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('networking_event', 'Networking Event'), ('skill_practice', 'Skill Practice'), ('course_completed', 'Course Completed'), ('mentor_session', 'Mentor Session'), ('job_research', 'Job Research'), ('resume_update', 'Resume Update'), ('linkedin_activity', 'LinkedIn Activity'), ('other', 'Other')], max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracker.goal')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracker.milestone')),
            ],
            options={
                'db_table': 'tracker_activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracker.habit')),
            ],
            options={
                'db_table': 'tracker_habit_entries',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('goals_active', models.PositiveIntegerField(default=0)),
                ('goals_completed', models.PositiveIntegerField(default=0)),
                ('milestones_completed', models.PositiveIntegerField(default=0)),
                ('activities_count', models.PositiveIntegerField(default=0)),
                ('habits_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('applications_submitted', models.PositiveIntegerField(default=0)),
                ('interviews_attended', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_progress_snapshots',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
    ]
